beam: 10
prediction_type: units
batch_size: 1
inference:
  command:
    - python
    - -m
    - direct_s2st.s2ut.fairseq_infer
    - --data-root
    - "{data_root}"
    - --run-root
    - "{run_root}"
    - --predictions
    - "{predictions}"
    - --common-root
    - "{common_root}"
