feature_extractor: hubert_base
hubert_layer: 6
kmeans_clusters: 100
sample_rate: 16000
reduce_consecutive_units: true
hubert:
  model: facebook/hubert-base-ls960
  revision: dba3bb02fda4248b6e082697eee756de8fe8aa8a
kmeans:
  artifact: fairseq-textless-hubert-base-l6-k100
  format: fairseq-joblib
  source_sklearn_version: "0.24.0"
  loader_sklearn_version: "1.5.2"
  source_url: https://dl.fbaipublicfiles.com/textless_nlp/gslm/hubert/km100/km.bin
  path: models/s2ut/hubert_base_l6_k100.bin
  sha256: f14a3104615485381fc489701d6761c9abbdbb0d43607cf55518a1e2891023fe
