beam: 10
batch_size: 1
inference:
  command:
    - python
    - -m
    - direct_s2st.translatotron2.fairseq_infer
    - --data-root
    - "{data_root}"
    - --run-root
    - "{run_root}"
    - --predictions
    - "{predictions}"
